### ISSUE TITLE
'csslint.' is not in the npm registry.

### ISSUE THREAD

**Issue by ishitaIndraneel** [tomastrajan/angular-js-es6-testing-example#13]
Hi , 
I am trying to install csslint through sublimeLinter.I keep getting the following error : 

Darwin 13.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "csslint."
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/csslint.
npm ERR! 404 
npm ERR! 404  'csslint.' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

Here is the content from the log file : 

node_modules/npm/node_modules/npm-registry-client/lib/request.js:280:14)
27 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:210:14)
27 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:187:22)
27 verbose stack     at emitTwo (events.js:106:13)
27 verbose stack     at Request.emit (events.js:191:7)
27 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1048:10)
27 verbose stack     at emitOne (events.js:96:13)
27 verbose stack     at Request.emit (events.js:188:7)
27 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:969:12)
28 verbose statusCode 404
29 verbose pkgid csslint.
30 verbose cwd /private/var/root
31 error Darwin 13.4.0
32 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "csslint."
33 error node v6.9.5
34 error npm  v3.10.10
35 error code E404
36 error 404 Registry returned 404 for GET on https://registry.npmjs.org/csslint.
37 error 404
38 error 404 'csslint.' is not in the npm registry.
39 error 404 You should bug the author to publish it (or use the name yourself!)
40 error 404 Note that you can also install from a
41 error 404 tarball, folder, http url, or git url.
42 verbose exit [ 1, true ]

**Comment by ishitaIndraneel** [comment]
Any help will be appreciated.
Thanks
